import  com.drool.examples.drools.dto.OrderRequest;

rule "Discount for CARD payment above 10000"
    when
        orderObject : OrderRequest( paymentType=="CARD" && totalPrice > 10000 );
    then
        orderObject.setDiscount(15);
end;

rule "Discount for CARD payment below 10000 and above 5000"
    when
        orderObject : OrderRequest( paymentType=="CARD" && totalPrice > 5000 && totalPrice < 10000 );
    then
        orderObject.setDiscount(5);
end;

rule "Discount for CARD payment below 5000"
    when
        orderObject : OrderRequest( paymentType=="CARD" && totalPrice <= 5000);
    then
        orderObject.setDiscount(0);
end;
